### ISSUE TITLE
Mod Request: FerriteCore

### ISSUE THREAD

**Issue by IronOxidizer** [ReperakPro/fabric-optimization-mods#36] opened 2021-06-08 11:50 UTC
**Requirements for a mod to be added:**
- [x]  The mod must be open-source.
- [x]  The mod cannot sacrifice vanilla behavior for performance.
- [x]  The mod must be actively maintained.

**Mod name:** FerriteCore

**Type of mod (e.g. rendering, lighting, extra):** Memory

**Repository (e.g. GitHub, GitLab, Gitea):** https://modrinth.com/mod/ferrite-core

**Developer/organization:** [malte0811](https://github.com/malte0811)

**Additional notes:**
Can be used along side Hydrogen for additional memory improvement. 

Coincidentally, I started working on a modpack around the same time as this project with a similar goal. It includes benchmarking and packaging / building. Feel free to check it out for more performance enhancing mods:

https://github.com/IronOxidizer/Fast-as-Fabric

**Comment by DragonEggBedrockBreaking** [comment] 2021-06-08 14:48
Duplicate of #2

**Closed** 2021-06-08 14:52 UTC
